
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 12 19:59:24 NZDT 2016
//----------------------------------------------------

package adams.parser.lookupupdate;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int AND = 27;
  public static final int LT = 20;
  public static final int ELSE = 4;
  public static final int PLUS = 8;
  public static final int OR = 28;
  public static final int RPAREN = 17;
  public static final int THEN = 3;
  public static final int SEMI = 15;
  public static final int DIVISION = 10;
  public static final int ALL = 13;
  public static final int NOT = 26;
  public static final int EXPONENT = 11;
  public static final int END = 5;
  public static final int VARIABLE = 31;
  public static final int TRUE = 18;
  public static final int MODULO = 12;
  public static final int IF = 2;
  public static final int GT = 22;
  public static final int LPAREN = 16;
  public static final int LE = 21;
  public static final int BOOLEAN = 30;
  public static final int STRING = 32;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int GE = 23;
  public static final int FALSE = 19;
  public static final int MINUS = 6;
  public static final int error = 1;
  public static final int EQ = 24;
  public static final int ASSIGNMENT = 14;
  public static final int NOT_EQ = 25;
  public static final int UMINUS = 7;
}

