
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 16 16:43:17 NZST 2019
//----------------------------------------------------

package adams.parser.mathematicalexpression;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ISNAN = 38;
  public static final int LEFT = 45;
  public static final int TIMES = 9;
  public static final int DIVISION = 10;
  public static final int GT = 62;
  public static final int REPLACEALL = 49;
  public static final int FLOOR = 21;
  public static final int TODAY = 72;
  public static final int MONTH = 74;
  public static final int UPPERCASE = 43;
  public static final int RIGHT = 46;
  public static final int ATAN = 31;
  public static final int WEEKDAY = 80;
  public static final int EXT = 57;
  public static final int GE = 63;
  public static final int LOWERCASE = 42;
  public static final int TANH = 30;
  public static final int EXP = 16;
  public static final int SIN = 17;
  public static final int SECOND = 78;
  public static final int HOUR = 76;
  public static final int YEAR = 73;
  public static final int COMMA = 2;
  public static final int RPAREN = 5;
  public static final int POW = 22;
  public static final int LT = 60;
  public static final int LPAREN = 4;
  public static final int NOW = 71;
  public static final int NOT = 66;
  public static final int FALSE = 59;
  public static final int LE = 61;
  public static final int LOG10 = 27;
  public static final int MIN = 24;
  public static final int STR = 55;
  public static final int CEIL = 23;
  public static final int TRIM = 40;
  public static final int SIGNUM = 34;
  public static final int EQ = 64;
  public static final int MID = 47;
  public static final int TAN = 19;
  public static final int LOG = 15;
  public static final int COSH = 28;
  public static final int NUMBER = 81;
  public static final int MODULO = 12;
  public static final int TRUE = 58;
  public static final int MATCHES = 44;
  public static final int PLUS = 8;
  public static final int BOOLEAN = 82;
  public static final int FIND = 51;
  public static final int VARIABLE = 83;
  public static final int CONCATENATE = 53;
  public static final int MAX = 25;
  public static final int MINUTE = 77;
  public static final int PROCEDURE = 87;
  public static final int WEEKNUM = 79;
  public static final int LENGTH = 39;
  public static final int PI = 69;
  public static final int E = 70;
  public static final int COS = 18;
  public static final int SEMICOLON = 3;
  public static final int EOF = 0;
  public static final int SUBSTITUTE = 50;
  public static final int FUNCTION = 86;
  public static final int REPEAT = 54;
  public static final int IFMISSING = 37;
  public static final int MINUS = 6;
  public static final int DATE = 85;
  public static final int IFELSE = 35;
  public static final int OR = 68;
  public static final int HAS = 36;
  public static final int RINT = 20;
  public static final int error = 1;
  public static final int CONTAINS = 52;
  public static final int ABS = 13;
  public static final int REPLACE = 48;
  public static final int NOT_EQ = 65;
  public static final int SINH = 29;
  public static final int DAY = 75;
  public static final int EXPONENT = 11;
  public static final int SQRT = 14;
  public static final int STRING = 84;
  public static final int CBRT = 26;
  public static final int AND = 67;
  public static final int REPLACEEXT = 56;
  public static final int UMINUS = 7;
  public static final int SUBSTR = 41;
  public static final int HYPOT = 33;
  public static final int ATAN2 = 32;
}

