/* The following code was generated by JFlex 1.4.3 on 3/07/16 7:43 PM */

/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * Scanner.java
 * Copyright (C) 2009-2015 University of Waikato, Hamilton, New Zealand
 */

package adams.parser.actorsuggestion;

import java_cup.runtime.SymbolFactory;
import java.io.*;
import java.util.*;

/**
 * A scanner for parsing actor suggestion rules.
 *
 * @author FracPete (fracpete at waikato dot ac dot nz)
 * @version $Revision$
 */

public class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\32\1\41\1\0\1\32\1\35\22\0\1\32\1\0\1\33"+
    "\1\0\1\25\3\0\1\30\1\31\4\0\1\27\1\0\12\26\7\0"+
    "\1\1\1\6\1\13\1\3\1\7\1\10\1\15\1\24\1\14\1\25"+
    "\1\23\1\16\1\22\1\2\1\4\1\12\1\25\1\5\1\20\1\11"+
    "\1\21\1\25\1\17\3\25\1\0\1\34\2\0\1\25\1\0\15\25"+
    "\1\37\3\25\1\40\1\25\1\36\6\25\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\13\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\4\2\1\0\1\2\1\12\10\2\1\13"+
    "\1\14\4\2\1\15\1\16\1\17\1\20\1\21\3\2"+
    "\1\22\27\2\1\23\1\24\7\2\1\25\1\26\3\2"+
    "\1\27\13\2\1\30\1\31\3\2\1\32\2\2\1\33"+
    "\1\2\1\34\1\2\1\35\4\2\1\36\3\2\1\37"+
    "\4\2\1\40\1\2\1\41\1\42\2\2\1\43\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\104\0\104"+
    "\0\104\0\104\0\u01dc\0\104\0\u01fe\0\u0220\0\u0242\0\u0264"+
    "\0\u0286\0\u02a8\0\u02ca\0\252\0\u02ec\0\u030e\0\u0330\0\u0352"+
    "\0\u0374\0\u0396\0\u03b8\0\u03da\0\252\0\u03fc\0\u041e\0\u0440"+
    "\0\u0462\0\u0484\0\104\0\104\0\104\0\104\0\252\0\u04a6"+
    "\0\u04c8\0\u04ea\0\252\0\u050c\0\u052e\0\u0550\0\u0572\0\u0594"+
    "\0\u05b6\0\u05d8\0\u05fa\0\u061c\0\u063e\0\u0660\0\u0682\0\u06a4"+
    "\0\u06c6\0\u06e8\0\u070a\0\u072c\0\u074e\0\u0770\0\u0792\0\u07b4"+
    "\0\u07d6\0\u07f8\0\252\0\252\0\u081a\0\u083c\0\u085e\0\u0880"+
    "\0\u08a2\0\u08c4\0\u08e6\0\252\0\252\0\u0908\0\u092a\0\u094c"+
    "\0\252\0\u096e\0\u0990\0\u09b2\0\u09d4\0\u09f6\0\u0a18\0\u0a3a"+
    "\0\u0a5c\0\u0a7e\0\u0aa0\0\u0ac2\0\252\0\252\0\u0ae4\0\u0b06"+
    "\0\u0b28\0\252\0\u0b4a\0\u0b6c\0\252\0\u0b8e\0\252\0\u0bb0"+
    "\0\252\0\u0bd2\0\u0bf4\0\u0c16\0\u0c38\0\252\0\u0c5a\0\u0c7c"+
    "\0\u0c9e\0\252\0\u0cc0\0\u0ce2\0\u0d04\0\u0d26\0\252\0\u0d48"+
    "\0\252\0\252\0\u0d6a\0\u0d8c\0\252\0\252";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\6\1\10\1\6"+
    "\1\11\1\12\1\13\1\6\1\14\1\15\2\6\1\16"+
    "\5\6\2\3\1\17\1\20\1\21\1\22\1\3\1\21"+
    "\3\6\1\21\33\23\1\24\1\25\1\3\3\23\44\0"+
    "\1\6\1\26\5\6\1\27\2\6\1\30\2\6\1\31"+
    "\10\6\1\32\6\0\3\6\2\0\3\6\1\33\22\6"+
    "\1\32\6\0\3\6\2\0\26\6\1\32\6\0\3\6"+
    "\2\0\4\6\1\34\21\6\1\32\6\0\3\6\2\0"+
    "\6\6\1\35\17\6\1\32\6\0\3\6\2\0\1\36"+
    "\2\6\1\37\14\6\1\40\5\6\1\32\6\0\3\6"+
    "\2\0\4\6\1\41\16\6\1\42\2\6\1\32\6\0"+
    "\3\6\2\0\1\43\3\6\1\44\21\6\1\32\6\0"+
    "\3\6\2\0\7\6\1\45\7\6\1\46\6\6\1\32"+
    "\6\0\3\6\2\0\6\6\1\47\17\6\1\32\6\0"+
    "\3\6\2\0\3\6\1\50\4\6\1\51\2\6\1\52"+
    "\12\6\1\32\6\0\3\6\1\0\33\23\3\0\3\23"+
    "\34\0\1\53\2\0\1\54\1\55\1\56\2\0\2\6"+
    "\1\57\23\6\1\32\6\0\3\6\2\0\10\6\1\60"+
    "\15\6\1\32\6\0\3\6\2\0\12\6\1\61\13\6"+
    "\1\32\6\0\3\6\2\0\15\6\1\62\10\6\1\32"+
    "\6\0\3\6\2\0\25\6\10\0\3\6\2\0\10\6"+
    "\1\63\15\6\1\32\6\0\3\6\2\0\7\6\1\64"+
    "\16\6\1\32\6\0\3\6\2\0\15\6\1\65\10\6"+
    "\1\32\6\0\3\6\2\0\15\6\1\66\10\6\1\32"+
    "\6\0\3\6\2\0\15\6\1\67\10\6\1\32\6\0"+
    "\3\6\2\0\1\70\17\6\1\71\5\6\1\32\6\0"+
    "\3\6\2\0\6\6\1\72\17\6\1\32\6\0\3\6"+
    "\2\0\4\6\1\73\21\6\1\32\6\0\3\6\2\0"+
    "\6\6\1\74\17\6\1\32\6\0\3\6\2\0\7\6"+
    "\1\75\5\6\1\76\10\6\1\32\6\0\3\6\2\0"+
    "\1\6\1\77\24\6\1\32\6\0\3\6\2\0\20\6"+
    "\1\100\5\6\1\32\6\0\3\6\2\0\1\101\25\6"+
    "\1\32\6\0\3\6\2\0\1\6\1\102\24\6\1\32"+
    "\6\0\3\6\2\0\6\6\1\103\17\6\1\32\6\0"+
    "\3\6\2\0\6\6\1\104\17\6\1\32\6\0\3\6"+
    "\2\0\3\6\1\105\22\6\1\32\6\0\3\6\2\0"+
    "\3\6\1\106\22\6\1\32\6\0\3\6\2\0\17\6"+
    "\1\107\6\6\1\32\6\0\3\6\2\0\15\6\1\110"+
    "\10\6\1\32\6\0\3\6\2\0\15\6\1\111\10\6"+
    "\1\32\6\0\3\6\2\0\1\6\1\112\24\6\1\32"+
    "\6\0\3\6\2\0\6\6\1\113\17\6\1\32\6\0"+
    "\3\6\2\0\1\6\1\114\24\6\1\32\6\0\3\6"+
    "\2\0\6\6\1\115\17\6\1\32\6\0\3\6\2\0"+
    "\12\6\1\116\13\6\1\32\6\0\3\6\2\0\13\6"+
    "\1\117\12\6\1\32\6\0\3\6\2\0\1\120\25\6"+
    "\1\32\6\0\3\6\2\0\6\6\1\121\17\6\1\32"+
    "\6\0\3\6\2\0\4\6\1\122\21\6\1\32\6\0"+
    "\3\6\2\0\1\6\1\123\24\6\1\32\6\0\3\6"+
    "\2\0\22\6\1\124\3\6\1\32\6\0\3\6\2\0"+
    "\4\6\1\125\21\6\1\32\6\0\3\6\2\0\11\6"+
    "\1\126\14\6\1\32\6\0\3\6\2\0\16\6\1\127"+
    "\7\6\1\32\6\0\3\6\2\0\4\6\1\130\21\6"+
    "\1\32\6\0\3\6\2\0\6\6\1\131\17\6\1\32"+
    "\6\0\3\6\2\0\3\6\1\132\22\6\1\32\6\0"+
    "\3\6\2\0\1\6\1\133\24\6\1\32\6\0\3\6"+
    "\2\0\17\6\1\134\6\6\1\32\6\0\3\6\2\0"+
    "\1\6\1\135\24\6\1\32\6\0\3\6\2\0\6\6"+
    "\1\136\17\6\1\32\6\0\3\6\2\0\4\6\1\137"+
    "\21\6\1\32\6\0\3\6\2\0\17\6\1\140\6\6"+
    "\1\32\6\0\3\6\2\0\4\6\1\141\21\6\1\32"+
    "\6\0\3\6\2\0\12\6\1\142\13\6\1\32\6\0"+
    "\3\6\2\0\2\6\1\143\23\6\1\32\6\0\3\6"+
    "\2\0\10\6\1\144\15\6\1\32\6\0\3\6\2\0"+
    "\17\6\1\145\6\6\1\32\6\0\3\6\2\0\6\6"+
    "\1\146\17\6\1\32\6\0\3\6\2\0\16\6\1\147"+
    "\7\6\1\32\6\0\3\6\2\0\1\150\25\6\1\32"+
    "\6\0\3\6\2\0\7\6\1\151\16\6\1\32\6\0"+
    "\3\6\2\0\10\6\1\152\15\6\1\32\6\0\3\6"+
    "\2\0\2\6\1\153\23\6\1\32\6\0\3\6\2\0"+
    "\17\6\1\154\6\6\1\32\6\0\3\6\2\0\10\6"+
    "\1\155\15\6\1\32\6\0\3\6\2\0\1\156\25\6"+
    "\1\32\6\0\3\6\2\0\6\6\1\157\17\6\1\32"+
    "\6\0\3\6\2\0\1\160\25\6\1\32\6\0\3\6"+
    "\2\0\17\6\1\161\6\6\1\32\6\0\3\6\2\0"+
    "\13\6\1\162\12\6\1\32\6\0\3\6\2\0\21\6"+
    "\1\163\4\6\1\32\6\0\3\6\2\0\3\6\1\164"+
    "\22\6\1\32\6\0\3\6\2\0\13\6\1\165\12\6"+
    "\1\32\6\0\3\6\2\0\10\6\1\166\15\6\1\32"+
    "\6\0\3\6\2\0\10\6\1\167\15\6\1\32\6\0"+
    "\3\6\2\0\15\6\1\170\10\6\1\32\6\0\3\6"+
    "\2\0\1\6\1\171\24\6\1\32\6\0\3\6\2\0"+
    "\6\6\1\172\17\6\1\32\6\0\3\6\2\0\4\6"+
    "\1\173\21\6\1\32\6\0\3\6\2\0\1\6\1\174"+
    "\24\6\1\32\6\0\3\6\2\0\6\6\1\175\17\6"+
    "\1\32\6\0\3\6\2\0\3\6\1\176\22\6\1\32"+
    "\6\0\3\6\2\0\14\6\1\177\11\6\1\32\6\0"+
    "\3\6\2\0\21\6\1\200\4\6\1\32\6\0\3\6"+
    "\2\0\14\6\1\201\11\6\1\32\6\0\3\6\2\0"+
    "\17\6\1\202\6\6\1\32\6\0\3\6\2\0\1\6"+
    "\1\203\24\6\1\32\6\0\3\6\2\0\6\6\1\204"+
    "\17\6\1\32\6\0\3\6\2\0\6\6\1\205\17\6"+
    "\1\32\6\0\3\6\2\0\4\6\1\206\21\6\1\32"+
    "\6\0\3\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3502];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\13\1\4\11\1\1\1\11\5\1\1\0"+
    "\20\1\4\11\130\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // Author: FracPete (fracpete at waikato dot ac dot nz)
  // Version: $Revision$
  protected SymbolFactory sf;

  public Scanner(InputStream r, SymbolFactory sf){
    this(r);
    this.sf = sf;
  }
  StringBuilder string = new StringBuilder();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 114) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 26: 
          { return sf.newSymbol("Parent" ,     sym.PARENT);
          }
        case 37: break;
        case 35: 
          { return sf.newSymbol("Standalone",  sym.STANDALONE);
          }
        case 38: break;
        case 3: 
          { return sf.newSymbol("Left Bracket",  sym.LPAREN);
          }
        case 39: break;
        case 23: 
          { return sf.newSymbol("False",       sym.FALSE);
          }
        case 40: break;
        case 14: 
          { string.append('\t');
          }
        case 41: break;
        case 6: 
          { string.setLength(0); yybegin(STRING);
          }
        case 42: break;
        case 25: 
          { return sf.newSymbol("Before",      sym.BEFORE);
          }
        case 43: break;
        case 36: 
          { return sf.newSymbol("Transformer", sym.TRANSFORMER);
          }
        case 44: break;
        case 5: 
          { /* ignore white space. */
          }
        case 45: break;
        case 31: 
          { return sf.newSymbol("Fullname",    sym.FULLNAME);
          }
        case 46: break;
        case 2: 
          { return sf.newSymbol("Classname", sym.CLASSNAME, new String(yytext()));
          }
        case 47: break;
        case 27: 
          { return sf.newSymbol("First",       sym.ISLAST);
          }
        case 48: break;
        case 9: 
          { string.append('\\');
          }
        case 49: break;
        case 16: 
          { string.append('\r');
          }
        case 50: break;
        case 11: 
          { return sf.newSymbol("If",          sym.IF);
          }
        case 51: break;
        case 4: 
          { return sf.newSymbol("Right Bracket", sym.RPAREN);
          }
        case 52: break;
        case 22: 
          { return sf.newSymbol("After",       sym.AFTER);
          }
        case 53: break;
        case 29: 
          { return sf.newSymbol("Accepts",     sym.ACCEPTS);
          }
        case 54: break;
        case 10: 
          { return sf.newSymbol("Or",          sym.OR);
          }
        case 55: break;
        case 13: 
          { string.append('\"');
          }
        case 56: break;
        case 8: 
          { yybegin(YYINITIAL);
                  return sf.newSymbol("Classname", sym.CMDLINE, string.toString());
          }
        case 57: break;
        case 33: 
          { return sf.newSymbol("Preceding" ,  sym.PRECEDING);
          }
        case 58: break;
        case 18: 
          { return sf.newSymbol("Not",         sym.NOT);
          }
        case 59: break;
        case 17: 
          { return sf.newSymbol("And",         sym.AND);
          }
        case 60: break;
        case 32: 
          { return sf.newSymbol("Following" ,  sym.FOLLOWING);
          }
        case 61: break;
        case 15: 
          { string.append('\n');
          }
        case 62: break;
        case 34: 
          { return sf.newSymbol("Generates",   sym.GENERATES);
          }
        case 63: break;
        case 7: 
          { string.append(yytext());
          }
        case 64: break;
        case 24: 
          { return sf.newSymbol("Allows",      sym.ALLOWS);
          }
        case 65: break;
        case 21: 
          { return sf.newSymbol("Sink",        sym.SINK);
          }
        case 66: break;
        case 20: 
          { return sf.newSymbol("Then",        sym.THEN);
          }
        case 67: break;
        case 1: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 68: break;
        case 30: 
          { return sf.newSymbol("First",       sym.ISFIRST);
          }
        case 69: break;
        case 19: 
          { return sf.newSymbol("True",        sym.TRUE);
          }
        case 70: break;
        case 28: 
          { return sf.newSymbol("Source",      sym.SOURCE);
          }
        case 71: break;
        case 12: 
          { return sf.newSymbol("Is",          sym.IS);
          }
        case 72: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {     return sf.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
