
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 22 11:04:19 NZDT 2016
//----------------------------------------------------

package adams.parser.actorsuggestion;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FOLLOWING = 5;
  public static final int AND = 22;
  public static final int CLASSNAME = 2;
  public static final int ALLOWS = 8;
  public static final int IS = 26;
  public static final int OR = 23;
  public static final int RPAREN = 19;
  public static final int SOURCE = 12;
  public static final int THEN = 21;
  public static final int ISFIRST = 6;
  public static final int NOT = 27;
  public static final int GENERATES = 9;
  public static final int TRUE = 16;
  public static final int IF = 20;
  public static final int LPAREN = 18;
  public static final int TRANSFORMER = 13;
  public static final int BOOLEAN = 15;
  public static final int ACCEPTS = 10;
  public static final int BEFORE = 24;
  public static final int EOF = 0;
  public static final int PRECEDING = 4;
  public static final int STANDALONE = 11;
  public static final int FALSE = 17;
  public static final int SINK = 14;
  public static final int error = 1;
  public static final int ISLAST = 7;
  public static final int AFTER = 25;
  public static final int PARENT = 3;
}

