
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 21 13:48:24 NZDT 2014
//----------------------------------------------------

package adams.parser.spreadsheetquery;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int REGEXP = 11;
  public static final int GE = 32;
  public static final int DESC = 39;
  public static final int LPAREN = 26;
  public static final int UPDATE = 3;
  public static final int IQR = 24;
  public static final int DELETE = 4;
  public static final int WHERE = 5;
  public static final int RPAREN = 27;
  public static final int MEDIAN = 20;
  public static final int AND = 36;
  public static final int NOT = 35;
  public static final int IS = 9;
  public static final int LT = 29;
  public static final int COLUMN = 41;
  public static final int OR = 37;
  public static final int COMMA = 25;
  public static final int SELECT = 2;
  public static final int MIN = 17;
  public static final int STDEV = 21;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int GROUP = 14;
  public static final int BY = 8;
  public static final int error = 1;
  public static final int LIMIT = 13;
  public static final int NULL = 10;
  public static final int NUMBER = 40;
  public static final int EQ = 33;
  public static final int ASC = 38;
  public static final int NOT_EQ = 34;
  public static final int ORDER = 7;
  public static final int SUM = 23;
  public static final int STRING = 42;
  public static final int STDEVP = 22;
  public static final int ALL = 28;
  public static final int COUNT = 16;
  public static final int AS = 12;
  public static final int AVERAGE = 19;
  public static final int MAX = 18;
  public static final int GT = 31;
  public static final int SET = 6;
  public static final int HAVING = 15;
}

