
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 03 12:22:05 NZDT 2018
//----------------------------------------------------

package adams.parser.booleanexpression;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ISNAN = 27;
  public static final int LEFT = 46;
  public static final int TIMES = 9;
  public static final int DIVISION = 10;
  public static final int GT = 61;
  public static final int FLOOR = 21;
  public static final int TODAY = 71;
  public static final int MONTH = 73;
  public static final int UPPERCASE = 44;
  public static final int RIGHT = 47;
  public static final int ATAN = 33;
  public static final int WEEKDAY = 79;
  public static final int EXT = 56;
  public static final int GE = 62;
  public static final int TANH = 32;
  public static final int LOWERCASE = 43;
  public static final int EXP = 16;
  public static final int GET = 40;
  public static final int SIN = 17;
  public static final int SECOND = 77;
  public static final int HOUR = 75;
  public static final int YEAR = 72;
  public static final int COMMA = 2;
  public static final int RPAREN = 5;
  public static final int POW = 22;
  public static final int LT = 59;
  public static final int LPAREN = 4;
  public static final int NOW = 70;
  public static final int FALSE = 58;
  public static final int NOT = 65;
  public static final int LE = 60;
  public static final int LOG10 = 29;
  public static final int MIN = 24;
  public static final int STR = 54;
  public static final int CEIL = 23;
  public static final int SIGNUM = 36;
  public static final int TRIM = 41;
  public static final int EQ = 63;
  public static final int MID = 48;
  public static final int TAN = 19;
  public static final int LOG = 15;
  public static final int COSH = 30;
  public static final int NUMBER = 80;
  public static final int MODULO = 12;
  public static final int TRUE = 57;
  public static final int MATCHES = 45;
  public static final int PLUS = 8;
  public static final int BOOLEAN = 81;
  public static final int FIND = 51;
  public static final int VARIABLE = 82;
  public static final int MAX = 25;
  public static final int CONCATENATE = 52;
  public static final int MINUTE = 76;
  public static final int PROCEDURE = 86;
  public static final int WEEKNUM = 78;
  public static final int LENGTH = 39;
  public static final int PI = 68;
  public static final int COS = 18;
  public static final int E = 69;
  public static final int EOF = 0;
  public static final int SEMICOLON = 3;
  public static final int SUBSTITUTE = 50;
  public static final int FUNCTION = 85;
  public static final int REPEAT = 53;
  public static final int MINUS = 6;
  public static final int IFMISSING = 38;
  public static final int DATE = 84;
  public static final int IFELSE = 26;
  public static final int OR = 67;
  public static final int RINT = 20;
  public static final int HAS = 37;
  public static final int error = 1;
  public static final int ABS = 13;
  public static final int REPLACE = 49;
  public static final int NOT_EQ = 64;
  public static final int SINH = 31;
  public static final int DAY = 74;
  public static final int EXPONENT = 11;
  public static final int SQRT = 14;
  public static final int STRING = 83;
  public static final int CBRT = 28;
  public static final int AND = 66;
  public static final int REPLACEEXT = 55;
  public static final int UMINUS = 7;
  public static final int SUBSTR = 42;
  public static final int HYPOT = 35;
  public static final int ATAN2 = 34;
}

