/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * TextDirectoryLoaderContainer.java
 * Copyright (C) 2021 University of Waikato, Hamilton, NZ
 */

package adams.gui.tools.wekainvestigator.data;

import adams.core.option.OptionUtils;
import weka.core.Instances;
import weka.core.converters.TextDirectoryLoader;

import java.io.Serializable;
import java.util.logging.Level;

/**
 * Dataset generated by TextDirectoryLoader.
 *
 * @author FracPete (fracpete at waikato dot ac dot nz)
 */
public class TextDirectoryLoaderContainer
  extends AbstractDataContainer {

  private static final long serialVersionUID = 6267905940957451551L;

  /** the generator used to load the data. */
  protected TextDirectoryLoader m_Loader;

  /**
   * Loads the data using the specified loader.
   *
   * @param loader	the loader to use
   */
  public TextDirectoryLoaderContainer(TextDirectoryLoader loader) {
    super();
    try {
      m_Data   = loader.getDataSet();
      m_Loader = loader;
    }
    catch (Exception e) {
      throw new IllegalArgumentException("Failed to load text data: " + OptionUtils.getCommandLine(loader), e);
    }
  }

  /**
   * Returns the source of the data item.
   *
   * @return		the source
   */
  @Override
  public String getSource() {
    if (m_Loader == null)
      return "<unknown>";
    else
      return OptionUtils.getCommandLine(m_Loader);
  }

  /**
   * Whether it is possible to reload this item.
   *
   * @return		true if reloadable
   */
  @Override
  public boolean canReload() {
    return (m_Loader != null);
  }

  /**
   * Reloads the data.
   *
   * @return		true if successfully reloaded
   */
  @Override
  protected boolean doReload() {
    try {
      m_Data = m_Loader.getDataSet();
      return true;
    }
    catch (Exception e) {
      getLogger().log(Level.SEVERE, "Failed to regenerate data: " + OptionUtils.getCommandLine(m_Loader), e);
      return false;
    }
  }

  /**
   * Returns the data to store in the undo.
   *
   * @return		the undo point
   */
  protected Serializable[] getUndoData() {
    return new Serializable[]{
      m_Data,
      m_Modified,
      m_Loader
    };
  }

  /**
   * Restores the data from the undo point.
   *
   * @param data	the undo point
   */
  protected void applyUndoData(Serializable[] data) {
    m_Data     = (Instances) data[0];
    m_Modified = (Boolean) data[1];
    m_Loader   = (TextDirectoryLoader) data[2];
  }

  /**
   * Cleans up data structures, frees up memory.
   */
  public void cleanUp() {
    super.cleanUp();
    m_Loader = null;
  }
}
