/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AbstractActualVsPredictedHtmlProcessor.java
 * Copyright (C) 2026 University of Waikato, Hamilton, New Zealand
 */

package adams.flow.transformer.actualvspredictedprocessor;

import adams.core.option.OptionUtils;

/**
 * Ancestor for processors that generate HTML output from a spreadsheet with
 * actual vs predicted data.
 *
 * @author fracpete (fracpete at waikato dot ac dot nz)
 */
public abstract class AbstractActualVsPredictedHtmlProcessor
  extends AbstractActualVsPredictedProcessor<String>
  implements ActualVsPredictedHtmlProcessor {

  private static final long serialVersionUID = -8506582556272777059L;

  /** the title to use. */
  protected String m_Title;

  /**
   * Adds options to the internal list of options.
   */
  @Override
  public void defineOptions() {
    super.defineOptions();

    m_OptionManager.add(
      "title", "title",
      "");
  }

  /**
   * Sets the title to use.
   *
   * @param value	the title
   */
  public void setTitle(String value) {
    m_Title = value;
    reset();
  }

  /**
   * Returns the title to use.
   *
   * @return		the title
   */
  public String getTitle() {
    return m_Title;
  }

  /**
   * Returns the tip text for this property.
   *
   * @return 		tip text for this property suitable for
   * 			displaying in the GUI or for listing the options.
   */
  public String titleTipText() {
    return "The title to use in the HTML.";
  }

  /**
   * Returns the type of output the processor generates.
   *
   * @return		the type of output
   */
  @Override
  public Class generates() {
    return String.class;
  }

  /**
   * Generates a comment with what was used to generate the output.
   *
   * @return		the comment
   */
  protected String generatedByAdams() {
    StringBuilder	result;

    result = new StringBuilder();
    result.append("<!--\n");
    result.append("  Generated by ADAMS using:\n");
    result.append("  ").append(OptionUtils.getCommandLine(this)).append("\n");
    result.append("-->\n");
    return result.toString();
  }
}
