
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 03 13:11:58 NZST 2016
//----------------------------------------------------

package adams.parser.templatesuggestion;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 17;
  public static final int CLASSNAME = 2;
  public static final int IS = 21;
  public static final int OR = 18;
  public static final int RPAREN = 14;
  public static final int SOURCE = 7;
  public static final int THEN = 16;
  public static final int ISFIRST = 4;
  public static final int NOT = 22;
  public static final int TRUE = 11;
  public static final int IF = 15;
  public static final int LPAREN = 13;
  public static final int TRANSFORMER = 8;
  public static final int BOOLEAN = 10;
  public static final int BEFORE = 19;
  public static final int EOF = 0;
  public static final int STANDALONE = 6;
  public static final int FALSE = 12;
  public static final int SINK = 9;
  public static final int ISLAST = 5;
  public static final int error = 1;
  public static final int AFTER = 20;
  public static final int PARENT = 3;
}

