
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 21 13:31:22 NZST 2015
//----------------------------------------------------

package adams.parser.spreadsheetformula;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LEFT = 38;
  public static final int TIMES = 9;
  public static final int DIVISION = 10;
  public static final int GT = 56;
  public static final int CELL_STRING = 51;
  public static final int FLOOR = 21;
  public static final int TODAY = 67;
  public static final int MONTH = 69;
  public static final int UPPERCASE = 48;
  public static final int RIGHT = 39;
  public static final int WEEKDAY = 75;
  public static final int GE = 57;
  public static final int LOWERCASE = 47;
  public static final int INTERCEPT = 37;
  public static final int EXP = 16;
  public static final int SIN = 17;
  public static final int SECOND = 73;
  public static final int HOUR = 71;
  public static final int YEAR = 68;
  public static final int COMMA = 2;
  public static final int SUM = 26;
  public static final int RPAREN = 5;
  public static final int POW = 22;
  public static final int LT = 54;
  public static final int LPAREN = 4;
  public static final int NOW = 66;
  public static final int FALSE = 53;
  public static final int NOT = 60;
  public static final int LE = 55;
  public static final int STDEVP = 31;
  public static final int MIN = 27;
  public static final int CEIL = 23;
  public static final int TRIM = 32;
  public static final int EQ = 58;
  public static final int MID = 40;
  public static final int TAN = 19;
  public static final int LOG = 15;
  public static final int NUMBER = 76;
  public static final int MODULO = 12;
  public static final int CELL_OBJECT = 50;
  public static final int TRUE = 52;
  public static final int MATCHES = 49;
  public static final int PLUS = 8;
  public static final int BOOLEAN = 77;
  public static final int SLOPE = 36;
  public static final int FIND = 43;
  public static final int MAX = 28;
  public static final int CONCATENATE = 44;
  public static final int COUNTIF = 33;
  public static final int MINUTE = 72;
  public static final int PROCEDURE = 82;
  public static final int WEEKNUM = 74;
  public static final int LENGTH = 25;
  public static final int PI = 64;
  public static final int COS = 18;
  public static final int E = 65;
  public static final int EOF = 0;
  public static final int SEMICOLON = 3;
  public static final int SUBSTITUTE = 42;
  public static final int FUNCTION = 81;
  public static final int REPEAT = 45;
  public static final int MINUS = 6;
  public static final int DATE = 80;
  public static final int IFELSE = 24;
  public static final int OR = 62;
  public static final int RINT = 20;
  public static final int error = 1;
  public static final int STDEV = 30;
  public static final int COUNTBLANK = 34;
  public static final int ABS = 13;
  public static final int REPLACE = 41;
  public static final int COLON = 63;
  public static final int NOT_EQ = 59;
  public static final int DAY = 70;
  public static final int CELL = 78;
  public static final int EXPONENT = 11;
  public static final int SQRT = 14;
  public static final int STRING = 79;
  public static final int AND = 61;
  public static final int SUMIF = 35;
  public static final int UMINUS = 7;
  public static final int SUBSTR = 46;
  public static final int AVERAGE = 29;
}

